import { useState } from 'react';
import { AlertCircle, CloudSun, Droplets, Wind } from 'lucide-react';
import { getForecast, WeatherApiError } from '../services/weatherApi';
import type { ForecastResponse } from '../types/weather';
import { conditionLabel, localeFor, t, useLanguage } from '../i18n';

export function ForecastCard({ date, low, high, description, humidity, wind, rain }: { date: string; low: number; high: number; description: string; humidity: number | null; wind: number | null; rain: number | null }) {
  const { language } = useLanguage();
  return <article className="rounded-2xl border border-line bg-white p-5 shadow-card"><p className="text-sm font-semibold text-muted">{new Date(date).toLocaleDateString(localeFor(language), { weekday: 'long', month: 'short', day: 'numeric', timeZone: 'UTC' })}</p><CloudSun className="my-4 text-brand" size={28} /><p className="text-sm capitalize text-ink">{conditionLabel(language, description)}</p><p className="mt-3 text-2xl font-semibold">{Math.round(high)}° <span className="text-base font-normal text-muted">/ {Math.round(low)}°C</span></p><div className="mt-4 space-y-2 text-xs text-muted">{humidity !== null && <p><Droplets className="mr-1 inline" size={13} />{t(language, 'Humidity')} {humidity}%</p>}{wind !== null && <p><Wind className="mr-1 inline" size={13} />{t(language, 'Wind')} {wind} m/s</p>}{rain !== null && <p>{t(language, 'Rain probability')} {Math.round(rain)}%</p>}</div></article>;
}

export default function Forecast() {
  const { language } = useLanguage();
  const [city, setCity] = useState('Dhule'); const [data, setData] = useState<ForecastResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { setData(await getForecast(city)); } catch (e) { setError(e instanceof WeatherApiError ? e.message : 'Unable to load forecast.'); } finally { setLoading(false); } }
  return <main id="main" className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><p className="text-xs font-semibold uppercase tracking-wider text-brand">{t(language, 'Forecast intelligence')}</p><h1 className="mt-3 text-3xl font-semibold">{t(language, 'Forecast')} · {data?.location.name ?? city}</h1><p className="mt-2 text-sm text-muted">{t(language, 'Provider forecast data for the next available days.')}</p><form className="mt-6 flex max-w-lg gap-3" onSubmit={(e) => { e.preventDefault(); void load(); }}><input aria-label={t(language, 'Location')} value={city} onChange={(e) => setCity(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-line bg-white px-4 py-3" /><button className="rounded-xl bg-brand px-5 py-3 font-medium text-white" disabled={loading}>{loading ? t(language, 'Loading') : t(language, 'Get forecast')}</button></form>{error && <p role="alert" className="mt-5 flex items-center gap-2 text-sm text-rose-700"><AlertCircle size={17}/>{error}</p>}{loading && <p role="status" className="mt-8 text-muted">{t(language, 'Loading forecast…')}</p>}{data && <><section className="mt-8 rounded-2xl border border-line bg-white p-5"><p className="font-semibold">{data.location.name}, {data.location.country}</p><p className="mt-1 text-xs text-muted">{t(language, 'Source')}: {data.source} · {t(language, 'Retrieved at')} {new Date(data.forecasted_at).toLocaleString(localeFor(language))}</p></section><section aria-label={t(language, 'Forecast')} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{data.forecast.map(day => <ForecastCard key={day.date} date={day.date} low={day.temperature_min} high={day.temperature_max} description={day.description} humidity={day.humidity} wind={day.wind_speed} rain={day.rain_probability} />)}</section><section className="mt-6 rounded-2xl border border-line bg-white p-5"><h2 className="font-semibold">{t(language, 'Temperature trend (°C)')}</h2><div className="mt-5 flex h-36 items-end gap-3" aria-label={t(language, 'Temperature trend (°C)')}>{data.forecast.map(day => <div key={day.date} className="flex flex-1 flex-col items-center gap-2"><span className="text-xs">{Math.round(day.temperature_max)}°</span><div className="w-full rounded-t-lg bg-brand/80" style={{ height: `${Math.max(16, Math.min(100, (day.temperature_max - Math.min(...data.forecast.map(x => x.temperature_min)) + 5) * 5))}%` }} /><span className="text-[10px] text-muted">{new Date(day.date).toLocaleDateString(localeFor(language), { weekday: 'short', timeZone: 'UTC' })}</span></div>)}</div></section></>}</main>;
}
